### ISSUE TITLE
No process info be displayed when running npm install 

### ISSUE THREAD

**Issue by hong19** [polintw/Pensieve#45]
# Problem
- When running npm install, it doesn't display the process information and halt for a long time(> 10 mins). 
- The following scripts only need run at the first time.  
```bash
mkdir -p ./faked/pics/1
mkdir -p ./faked/logs
mkdir -p ./faked/dbSeeds
cp ./config/.env.example.json ./config/.env.json
```

# Design overview
Separate the build process into two parts: 
-  set up process before npm install
- `npm install`

There two approachs: 
- use npm `preinstall` script
- use `grunt`

**Comment by polintw** [comment]
so, now I can take it as a solved issue since you had seperated them under PR #48, using the approach "use a 'setUp' script" ?
