### ISSUE TITLE
Wrong path of saving img in development

### ISSUE THREAD

**Issue by hong19** [polintw/Pensieve#63]
In when uploading images, the sever save them in `pics1/`, but retrieve in `pics/1/`. It caused file not found errors. 

![Screen Shot 2019-12-01 at 8 54 10 PM](https://user-images.githubusercontent.com/4393046/69914243-cf9e9c00-147c-11ea-9ba2-5d9182c55485.png)

**Comment by polintw** [comment]
Got it!

Already fixed it in the latest commit on branch develop.
